[package]
name = "download-station-companion"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.9",  features = ["blocking", "json"]}
log = "0.4.22"
serde_json = "1.0.134"
dotenv = "0.15.0"
derive-new = "0.7.0"
lazy_static = "1.5.0"
