name: Release

on:
  push:
    tags:
        - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:    
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release      
      - name: Upload Release Asset
        id: upload-release-asset 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/releases/${{ github.ref_name }}/assets?name=ds-companion" \
            --data-binary "@./target/release/ds-companion"
