name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Fake .env
        run: cp .env.example .env 
      - name: Build
        run: cargo build --verbose
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust


  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
  
